server:
<<<<<<< HEAD
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/iClassPass?autoReconnect=true&useSSL=false
    username: root
    password: root
=======
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fullstack
    username: root
    password: GigaTorb123
>>>>>>> 174258d294c2c787554ed0cfe8d7433712b038e3

jwt:
  secret: gigatorb