#server:
#  port: 8080
#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/iClassPass?autoReconnect=true&useSSL=false
#    username: root
#    password: root
#
#
#
#jwt:
#  secret: gigatorb